version: '3.9'

services:
  postgres:
    container_name: postgres_container
    image: postgres:alpine
    ports:
      - 5432:5432
    env_file:
      - postgres.env
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/
    volumes:
       - ./volumes/postgres/data/:/var/lib/postgresql/data/
    restart: unless-stopped
  
  redis:
    container_name: redis_container
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis/data:/data
    restart: unless-stopped
  
  # RabbitMQ Management Panel: http://localhost:15672 user:guest pass:guest
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
    restart: unless-stopped

  nginx: 
    container_name: nginx_container
    image: nginx:alpine
    volumes:
      - ./volumes/nginx/templates:/etc/nginx/templates
    ports:
      - 8080:3000
      - 443:443

  adminer:
    container_name: adminer_container
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 15001:8080
    depends_on:
      - postgres
