version: '3.9'

services:  
  # RabbitMQ Management Panel: http://localhost:15672 user:guest pass:guest
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
    restart: unless-stopped
