services:
  steamos:
    image: lscr.io/linuxserver/steamos:latest
    container_name: steamos
    hostname: titan
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined #optional
    env_file:
      - .env
    volumes:
      - ./volumes/steamos/config:/config
      - /dev/input:/dev/input #optional
      - /run/udev/data:/run/udev/data #optional
    ports:
      - 3000:3000
      - 3001:3001
      - 27031:27031/udp
      - 27031:27031
      - 47984-47990:47984-47990 #optional
      - 48010-48010:48010-48010 #optional
      - 47998-48000:47998-48000/udp #optional
    devices:
      - /dev/dri:/dev/dri
    shm_size: "1gb"
    restart: unless-stopped

