version: '3.9'

services:  
  redis:
    container_name: redis_container
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis/data:/data
    restart: unless-stopped
